export const actionType = {
  ADD_TIME_DISPLAY: 'ADD_TIME_DISPLAY',
  REMOVE_TIME_DISPLAY: 'REMOVE_TIME_DISPLAY',
  CLEAR_ALL_DISPLAY: 'CLEAR_ALL_DISPLAY',
  ADD_LOCATION_WEATHER: 'ADD_LOCATION_WEATHER',
};
